#**BUSINESS PROBLEM**

In the telecom sector, a massive quantity of information is being generated on a day
by day foundation because of a sizable customer base. Decision makers and
commercial enterprise analysts emphasized that achieving new clients is dearer than
maintaining the present ones. Business analysts and purchaser dating management
analyzers want to recognize the reason behind churning clients.

#**SOLUTION APPROACH**

Churn prediction model that uses classification, as well as, techniques to identify the
churn customers and provides the factors behind the churning of customers in the
telecom sector.

We will train our machine learning model using random forest to
learn the patterns in the churn data.

In [4]:
# importing the libraries
import numpy as np
import pandas as pd

In [2]:
# import the dataset
churn_data = pd.read_csv("customer_churn.csv")

In [3]:
# displaying the top records
churn_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
# to understand the shape of the data
churn_data.shape

(7043, 21)

In [6]:
# to get the overview of the data
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
# to get the descriptive statistical summary
churn_data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [9]:
# to include categorical columns in descriptive statistical summary
churn_data.describe(include = "O").T

                 count unique               top  freq
customerID        7043   7043        7590-VHVEG     1
gender            7043      2              Male  3555
Partner           7043      2                No  3641
Dependents        7043      2                No  4933
PhoneService      7043      2               Yes  6361
MultipleLines     7043      3                No  3390
InternetService   7043      3       Fiber optic  3096
OnlineSecurity    7043      3                No  3498
OnlineBackup      7043      3                No  3088
DeviceProtection  7043      3                No  3095
TechSupport       7043      3                No  3473
StreamingTV       7043      3                No  2810
StreamingMovies   7043      3                No  2785
Contract          7043      3    Month-to-month  3875
PaperlessBilling  7043      2               Yes  4171
PaymentMethod     7043      4  Electronic check  2365
TotalCharges      7043   6531                      11
Churn             7043      2                No  5174

In [10]:
# to check the count of null values
churn_data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
# to get the categorcial count of a column
churn_data['PaymentMethod'].value_counts()

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [11]:
churn_data["TotalCharges"].value_counts()

TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

In [13]:
a = " "

In [14]:
type(a)

str

In [15]:
churn_data[churn_data["TotalCharges"] == " "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [17]:
#pd.to_numeric
# changing the object data to numeric data
churn_data["TotalCharges"] = pd.to_numeric(churn_data["TotalCharges"], errors = "coerce")

In [18]:
churn_data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [19]:
churn_data["SeniorCitizen"].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [20]:
# to remove the null values
churn_data = churn_data.dropna()

In [21]:
churn_data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [22]:
churn_data.shape

(7032, 21)

In [24]:
churn_data.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [23]:
churn_data.drop(columns=["customerID"], inplace = True)

In [25]:
# extracting all the object type columns for encoding
col_list = []

for i in churn_data.columns:
  if((churn_data[i].dtype == "object") & (i != "Churn")):
    col_list.append(i)

col_list

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

#**LABEL ENCODING**

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
#gender
#churn_data["gender"] = le.fit_transform(churn_data["gender"])

In [27]:
for i in col_list:
  churn_data[i] = le.fit_transform(churn_data[i])

In [28]:
churn_data.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,No
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,No
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,Yes
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,No
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,Yes
5,0,0,0,0,8,1,2,1,0,0,2,0,2,2,0,1,2,99.65,820.50,Yes
6,1,0,0,1,22,1,2,1,0,2,0,0,2,0,0,1,1,89.10,1949.40,No
7,0,0,0,0,10,0,1,0,2,0,0,0,0,0,0,0,3,29.75,301.90,No
8,0,0,1,0,28,1,2,1,0,0,2,2,2,2,0,1,2,104.80,3046.05,Yes
9,1,0,0,1,62,1,0,0,2,2,0,0,0,0,1,0,0,56.15,3487.95,No

In [29]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   int64
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   int64
 3   Dependents        7032 non-null   int64
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   int64
 6   MultipleLines     7032 non-null   int64
 7   InternetService   7032 non-null   int64
 8   OnlineSecurity    7032 non-null   int64
 9   OnlineBackup      7032 non-null   int64
 10  DeviceProtection  7032 non-null   int64
 11  TechSupport       7032 non-null   int64
 12  StreamingTV       7032 non-null   int64
 13  StreamingMovies   7032 non-null   int64
 14  Contract          7032 non-null   int64
 15  PaperlessBilling  7032 non-null   int64
 16  PaymentMethod     7032 non-null   int64
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(17), object(1)
memory usage: 1.1+ MB

In [30]:
# Dividing my data into X and y
X = churn_data.iloc[:,:-1]  # features
y = churn_data["Churn"]

In [31]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50

In [32]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7032, dtype: object

In [33]:
# splitting my data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [34]:
from random import Random
# Building the random forest model

from sklearn.ensemble import RandomForestClassifier

classifier1 = RandomForestClassifier(n_estimators = 100)  #number of decision trees = 100
classifier1.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
y_pred = classifier1.predict(X_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_pred,y_test)

0.7860696517412935

In [38]:
n = [100,200,300,400,500,600,700,800,900,1000]
accuracy = []
for i in n:
  model = RandomForestClassifier(n_estimators = i)
  model.fit(X_train,y_train)  # training the model
  pred = model.predict(X_test) # testing the model
  a = accuracy_score(y_test,pred) *100
  accuracy.append(a)

In [39]:
accuracy

[78.74911158493248,
 78.96233120113718,
 79.38877043354655,
 79.1044776119403,
 79.1044776119403,
 78.89125799573561,
 79.1044776119403,
 79.1044776119403,
 78.67803837953092,
 79.17555081734187]

In [40]:
d = {"Number of trees": n,
     "Accuracy" : accuracy}
df = pd.DataFrame(d)
df

   Number of trees   Accuracy
0              100  78.749112
1              200  78.962331
2              300  79.388770
3              400  79.104478
4              500  79.104478
5              600  78.891258
6              700  79.104478
7              800  79.104478
8              900  78.678038
9             1000  79.175551

In [ ]:
# OOB dataset

In [41]:
# Specify the target column and the feature columns
target_column = churn_data["Churn"]
feature_columns = churn_data.iloc[:,:-1] # features

# Extract the target variable
y = churn_data["Churn"]
X = churn_data.iloc[:,:-1]

# Create a random forest classifier with a desired number of trees (n_estimators)
rf_classifier = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=42)

# Fit the random forest on the data
rf_classifier.fit(X, y)

# Access the OOB dataset indices
oob_dataset_indices = np.where(rf_classifier.oob_decision_function_[:, 1] >= 0.5)

# Get the actual OOB dataset
oob_dataset = X.iloc[oob_dataset_indices]

# Print the OOB dataset
print("Out-of-Bag Dataset:")
oob_dataset

Out-of-Bag Dataset:

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
5,0,0,0,0,8,1,2,1,0,0,2,0,2,2,0,1,2,99.65,820.50
8,0,0,1,0,28,1,2,1,0,0,2,2,2,2,0,1,2,104.80,3046.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7013,0,0,0,0,40,1,2,1,0,2,2,0,2,0,0,1,0,93.40,3756.40
7018,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,1,3,70.65,70.65
7029,0,1,0,0,6,0,1,0,0,0,0,0,2,2,0,1,2,44.40,263.05
7032,1,1,0,0,1,1,2,1,0,0,0,0,0,0,0,1,2,75.75,75.75
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60

In [42]:
# OOB error

from sklearn.ensemble import RandomForestClassifier
classifier1 = RandomForestClassifier(n_estimators=100, oob_score=True)#n estimator is num of trees
classifier1.fit(X_train,y_train)
oob_error = 1 - classifier1.oob_score_
oob_error

0.20924444444444446

In [53]:
classifier1.oob_score_

0.7907555555555555

In [43]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

c_parameter_name = "max_depth"
c_parameter_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

results = []

for i in c_parameter_values:
    model = RandomForestClassifier(max_depth=i)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc_score = accuracy_score(y_pred, y_test) * 100
    results.append({"max_depth": i, "accuracy": acc_score})

df1 = pd.DataFrame(results)

In [44]:
df1

    max_depth   accuracy
0           1  73.773987
1           2  77.611940
2           3  79.459844
3           4  79.957356
4           5  79.673063
5           6  79.886283
6           7  80.099502
7           8  79.886283
8           9  80.170576
9          10  80.170576
10         11  79.246624
11         12  80.312722
12         13  80.099502
13         14  79.317697
14         15  78.962331

# Hyper Parameter tuning

Hyperparameter tuning refers to the process of selecting the optimal values for the hyperparameters of a machine learning model.

**max depth ->**
max_depth is a parameter in decision tree algorithms that specifies the maximum depth or maximum number of levels allowed in the decision tree.

**min_samples_split -> default=2**

->min_samples_split is a parameter in decision tree algorithms
that determines the minimum number of samples required to split an internal node.
->It specifies the minimum number of samples that should be present in a node for the algorithm to consider splitting it further.

**min_samples_leaf -> default = 1**
-> min_samples_leaf is another parameter in decision tree algorithms that determines the minimum number of samples required to be present in a leaf node.
-> It specifies the minimum number of samples that should be in a leaf for the algorithm to consider it as a valid leaf node.

**n_estimators** -> Number of trees

**max_features** -> the number of features to consider when looking for a best split

In [45]:
# Grid Search CV

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search

'''param_grid = {
  "n_estimators" : [100,200,300],
  "max_depth" : [None,5,10],
  "min_samples_split" : [2,5,10],
  "min_samples_leaf" : [1,2,4],
  "max_features" : ["sqrt", "log2"]
  "bootstrap" : [True,False]
  "criterion" : ["gini", "entropy" ]
} '''

param_grid = {
    "n_estimators" : [100,200,300],
  "max_depth" : [None,5,10],
  "min_samples_split" : [2,5,10],
  "min_samples_leaf" : [1,2,4],
  "criterion" : ["gini", "entropy" ]

}

In [46]:
classifier2 = RandomForestClassifier(random_state = 0)

# Perform grid search using cross validation

grid_search = GridSearchCV(estimator = classifier2, param_grid = param_grid, cv = 2 )
grid_search.fit(X_train,y_train)

GridSearchCV(cv=2, estimator=RandomForestClassifier(random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]})

In [47]:
grid_search.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=0)

In [48]:
print(grid_search.best_params_)

{'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}

In [49]:
from sklearn.ensemble import RandomForestClassifier

classifier3 = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', max_depth = 10, min_samples_leaf = 1, min_samples_split = 5)
classifier3.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, min_samples_split=5)

In [50]:
y_pred1 = classifier3.predict(X_test)
y_pred1

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [51]:
accuracy_score(y_pred1,y_test)

0.7995735607675906